#iOS 15 | iPad Air 3
name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
    - name: List Runtimes
      run: xcrun simctl list runtimes
    # - name: Build
    #   run: xcodebuild build -project GithubActionTest.xcodeproj -scheme "GithubActionTest" -destination "platform=iOS Simulator,OS=13.5,name=iPhone 8" 