name: BuildAndTestCI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4'

    - uses: actions/checkout@v2
    
    # - name: Force Xcode 11
    #   run: sudo xcode-select -switch /Applications/Xcode_13.0.app


    - name: List Runtimes
      run: xcrun simctl list runtimes

    - name: List iOS Simulator
      run: xcrun simctl list

    - name: Build
      run: xcodebuild clean build -project GithubActionTest.xcodeproj -scheme "GithubActionTest" -destination "platform=iOS Simulator,OS=14.4,name=iPad Air (3rd generation)" 
