name: BuildAndTestCI
on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: Build and Test
        run:  xcodebuild clean build test -project receiving/receiving.xcodeproj -scheme "receiving" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone X"
