name: BuildAndTestCI
on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
      - name: Build and Test
        run:  xcodebuild build test -project GithubActionTest.xcodeproj -scheme "GithubActionTest" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=Any iOS Simulator Device"