name: BuildAndTestCI
on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      # - uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: '11.7'

      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app

      - name: Build and Test
        run:  xcodebuild build test -project GithubActionTest.xcodeproj -scheme "GithubActionTest" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (4th generation),OS=13.7"
